repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.5'
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
    - id: poetry-check
