repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        types_or: [ python, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, jupyter ]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
    - id: poetry-check
  - repo: https://github.com/kynan/nbstripout
    rev: '0.7.1'
    hooks:
    - id: nbstripout
