services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    container_name: api
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./src:/api/app/src

  argilla:
    # loosely adapted from
    # https://github.com/argilla-io/argilla/blob/a88c81879d7088413912e6c368eee8ae77e840a9/docker/docker-compose.yaml
    image: argilla/argilla-server:latest
    container_name: argilla
    restart: unless-stopped
    ports:
      - 6900:6900
    environment:
      ARGILLA_HOME_PATH: /var/lib/argilla
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
    env_file:
      - .env
    depends_on:
      - elasticsearch
    volumes:
      - argilla_data:/var/lib/argilla

volumes:
  elasticsearch_data:
  argilla_data:
